project_id = "upqvgtuxfzsrwjahklij"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.generate-booking-changes-report]
verify_jwt = false
