import { format } from "date-fns";
import { Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import html2pdf from "html2pdf.js";

interface WeeklyChange {
  id: string;
  timestamp: string;
  operation_type: string;
  booking_id: string;
  customer_name: string;
  tour_name: string;
  user_name: string;
  details?: any;
}

interface BookingChangesReportPDFProps {
  changes: WeeklyChange[];
  period: string;
}

const formatOperationType = (type: string, details?: any): string => {
  const typeMap: Record<string, string> = {
    'CREATE': 'New Booking',
    'CREATE_BOOKING': 'New Booking',
    'ADD_HOTEL_TO_BOOKING': 'Hotel Added',
    'REMOVE_HOTEL_FROM_BOOKING': 'Hotel Removed',
    'ADD_ACTIVITY_TO_BOOKING': 'Activity Added',
    'REMOVE_ACTIVITY_FROM_BOOKING': 'Activity Removed',
    'DELETE_BOOKING': 'Booking Deleted',
    'CANCEL_BOOKING': 'Booking Cancelled',
  };
  
  if (type === 'UPDATE_HOTEL_BOOKING' && details?.hotel_dates) {
    const changes = [];
    if (details.hotel_dates.old?.check_in !== details.hotel_dates.new?.check_in) {
      changes.push(`check-in changed`);
    }
    if (details.hotel_dates.old?.check_out !== details.hotel_dates.new?.check_out) {
      changes.push(`check-out changed`);
    }
    if (changes.length > 0) {
      return `Hotel Updated: ${changes.join(', ')}`;
    }
    return 'Hotel Updated';
  }
  
  if (type === 'UPDATE_ACTIVITY_BOOKING') {
    return 'Activity Updated';
  }
  
  if (type === 'UPDATE_ACTIVITIES_CONSOLIDATED') {
    return 'Activities Updated';
  }
  
  return typeMap[type] || type;
};

const generateHTML = (changes: WeeklyChange[], period: string): string => {
  const currentDate = format(new Date(), 'dd/MM/yyyy');
  
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Booking Changes Report</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #333;
          }
          .header h1 {
            margin: 0 0 10px 0;
            font-size: 24px;
          }
          .header p {
            margin: 5px 0;
            color: #666;
            font-size: 14px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            background-color: #f5f5f5;
            padding: 12px;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid #ddd;
            font-size: 12px;
          }
          td {
            padding: 10px 12px;
            border-bottom: 1px solid #eee;
            font-size: 11px;
          }
          tr:hover {
            background-color: #f9f9f9;
          }
          .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
          }
          .summary {
            margin-top: 20px;
            padding: 15px;
            background-color: #f9f9f9;
            border-left: 4px solid #333;
          }
          .summary strong {
            display: block;
            margin-bottom: 5px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Booking Changes Report</h1>
          <p>Report Period: Last ${period} Days</p>
          <p>Generated: ${currentDate}</p>
        </div>
        
        <table>
          <thead>
            <tr>
              <th style="width: 18%">Date & Time</th>
              <th style="width: 22%">Customer</th>
              <th style="width: 25%">Tour</th>
              <th style="width: 20%">Action</th>
              <th style="width: 15%">Changed By</th>
            </tr>
          </thead>
          <tbody>
            ${changes.map(change => `
              <tr>
                <td>${format(new Date(change.timestamp), 'dd/MM/yyyy HH:mm')}</td>
                <td>${change.customer_name}</td>
                <td>${change.tour_name}</td>
                <td>${formatOperationType(change.operation_type, change.details)}</td>
                <td>${change.user_name}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        
        <div class="summary">
          <strong>Total Changes: ${changes.length}</strong>
        </div>
        
        <div class="footer">
          <p>This report was automatically generated by the Tour Operations Management System.</p>
        </div>
      </body>
    </html>
  `;
};

export const BookingChangesReportPDF = ({ changes, period }: BookingChangesReportPDFProps) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    try {
      const htmlContent = generateHTML(changes, period);
      const filename = `booking-changes-report-${period}-days-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
      
      const opt = {
        margin: 10,
        filename: filename,
        image: { type: 'jpeg' as const, quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' as const }
      };
      
      await html2pdf().set(opt).from(htmlContent).save();
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Button onClick={handleDownload} disabled={isGenerating}>
      {isGenerating ? (
        <>
          <Loader2 className="h-4 w-4 animate-spin" />
          Generating PDF...
        </>
      ) : (
        <>
          <Download className="h-4 w-4" />
          Download PDF
        </>
      )}
    </Button>
  );
};
