// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-tours.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/list-tours.ts
var list_tours_default = defineTool({
  name: "list_tours",
  title: "List tours",
  description: "List tours the signed-in user can access, most recent start date first. Optionally filter by a name/location search term or status.",
  inputSchema: {
    search: z.string().optional().describe("Case-insensitive match against tour name or location."),
    status: z.string().optional().describe("Filter by tour status (e.g. active, cancelled, archived)."),
    limit: z.number().int().optional().describe("Maximum number of tours to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const capped = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("tours").select(
      "id, name, location, start_date, end_date, status, capacity, tour_host, tour_type"
    ).order("start_date", { ascending: false }).limit(capped);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`name.ilike.%${search}%,location.ilike.%${search}%`);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tours: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-tour.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_tour_default = defineTool2({
  name: "get_tour",
  title: "Get tour details",
  description: "Fetch full details for a single tour by its id, including dates, pricing, capacity and host.",
  inputSchema: {
    tour_id: z2.string().describe("The tour id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tour_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("tours").select(
      "id, name, location, start_date, end_date, days, nights, status, capacity, minimum_passengers_required, tour_host, tour_type, price_single, price_double, price_twin, deposit_required, notes"
    ).eq("id", tour_id).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Tour not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tour: data }
    };
  }
});

// src/lib/mcp/tools/list-bookings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_bookings_default = defineTool3({
  name: "list_bookings",
  title: "List bookings for a tour",
  description: "List bookings for a given tour id, including passenger counts, status and accommodation dates.",
  inputSchema: {
    tour_id: z3.string().describe("The tour id (uuid) to list bookings for."),
    status: z3.string().optional().describe("Optional booking status filter (e.g. paid, deposited, waitlist)."),
    limit: z3.number().int().optional().describe("Maximum number of bookings to return (default 100, max 500).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tour_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const capped = Math.min(Math.max(limit ?? 100, 1), 500);
    let query = supabaseForUser(ctx).from("bookings").select(
      "id, tour_id, group_name, passenger_count, passenger_2_name, passenger_3_name, status, accommodation_required, check_in_date, check_out_date, total_nights, booking_agent"
    ).eq("tour_id", tour_id).order("created_at", { ascending: false }).limit(capped);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "upqvgtuxfzsrwjahklij";
var mcp_default = defineMcp({
  name: "art-tour-manager-mcp",
  title: "Australian Racing Tours MCP",
  version: "0.1.0",
  instructions: "Tools for the Australian Racing Tours tour manager. Use `list_tours` to find tours, `get_tour` for full details, and `list_bookings` to see bookings on a tour. All access is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tours_default, get_tour_default, list_bookings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
