// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmukjnykjidbpfmtzelx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdWtqbnlramlkYnBmbXR6ZWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDYwOTgsImV4cCI6MjA2NTAyMjA5OH0.HO-mv3bdaDiFobfkMmQWhR6Q-13pTe6aLJ0mlrfXOGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);